server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;   # Vue 路由刷新不 404
    }
    location /api/ {
        proxy_pass http://gateway:9000;     # 接口转发给网关（服务名互访）
    }
}