server:
  port: 8082
spring:
  application:
    name: question-service
  datasource:
    url: jdbc:mysql://localhost:3306/smart_interview?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost     # Redis 地址
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
